cask "1password"
cask "1password-cli"
cask "lastfm"
cask "opera-gx"
cask "rectangle"
cask "wezterm"
cask "discord"
cask "slack"
cask "betterdiscord-installer"
cask "skype"
cask "zoom"
cask "logitech-options"
cask "alfred"
cask "dropbox"



brew "btop"
brew "chezmoi"
brew "neovim", args: ["HEAD"]
brew "starship"
brew "bat"
brew "exa"
brew "k9s"
brew "fish"
brew "lazygit"
brew "gnupg"
brew "age"
brew "the_silver_searcher"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "zoxide"
brew "zellij"
brew "git"
brew "git-extras"
brew "gh"
brew "glab"
brew "git-delta"
brew "editorconfig"
brew "openconnect"
