customCommands:
  - key: "<c-m>"
    command: "glab mr create --fill"
    context: "global"
    description: "Create new MR (fill from branch name)"
    loadingText: "Creating merge request..."

  - key: "<c-l>"
    command: "glab mr list"
    context: "global"
    description: "List merge requests"
    loadingText: "Loading merge requests..."
    stream: true

  - key: "<c-c>"
    command: "glab mr close {{.SelectedRemoteBranch}}"
    context: "remoteBranches"
    description: "Close MR for current branch"
    loadingText: "Closing merge request..."

  - key: "<c-M>"
    command: "glab mr view"
    context: "global"
    description: "View current MR in browser"
    loadingText: "Opening merge request in browser..."
